In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [48]:
# There are two ways to make a sequential model
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

In [32]:
print(y)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [33]:
# 2nd way
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")


# Call layers on a test input
x = tf.ones((3, 3))
y = (layer2(layer1(x)))


In [34]:
print(y)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [35]:
model.layers

In [36]:
model.add(layers.Dense(4))

In [39]:
print(model.layers)

[<tensorflow.python.keras.layers.core.Dense object at 0x7eff4ba08a58>, <tensorflow.python.keras.layers.core.Dense object at 0x7eff4ba115f8>, <tensorflow.python.keras.layers.core.Dense object at 0x7eff4b9cac88>]


In [40]:
model.pop()
print(len(model.layers)) 

2


In [42]:
# No weights cz we haven't specified the inputs
layer = layers.Dense(3)
layer.weights  # Empty

[]

In [45]:
input = tf.zeros([2,2])
y = layer(input)
layer.weights

[<tf.Variable 'dense_8/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.6621507 , -0.65823805,  0.16427791],
        [-0.88167566, -0.04466426, -0.21892482]], dtype=float32)>,
 <tf.Variable 'dense_8/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [46]:
# Bias terms are zero ^

In [49]:
model.summary() #Input layer is not displayed

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               multiple                  8         
_________________________________________________________________
dense_9 (Dense)              multiple                  9         
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________
